trigger: none
pr:
  - fasttrack/*

parameters:
  - name: buildConfiguration
    type: object
    default:
    - name: "AMD64"
      agentPool: "mariner-core-x64-1es-mariner2-gpt-test"
      agentVMName: "Mariner-Build-Mariner2-1ES-Managed-Image2-GPT-Test"
    - name: "ARM64"
      agentPool: "mariner-core-arm64-1es-mariner2"
      agentVMName: "Mariner-Build-Mariner2-1ES-ARM64-Managed-Image"

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates
  parameters:
    featureFlags:
      runOnHost: true
    globalSdl:
      credscan:
        suppressionsFile: .config/CredScanSuppressions.json
    stages:
      - ${{ each configuration in parameters.buildConfiguration }}:
        - stage: Toolchain_${{ configuration.name }}
          jobs:
            - job: Build
              pool:
                type: linux
                isCustom: true
                name: ${{ configuration.agentPool }}
                vmImage: ${{ configuration.agentVMName }}
              steps:
                - template: .pipelines/templates/ToolchainBuild.yml@self

        - stage: RPMs_${{ configuration.name }}
          dependsOn: Toolchain_${{ configuration.name }}
          jobs:
            - job: Build
              pool:
                type: linux
                isCustom: true
                name: ${{ configuration.agentPool }}
                vmImage: ${{ configuration.agentVMName }}
              strategy:
                matrix:
                  regular:
                    runCheck: 'false'
                  ptest:
                    runCheck: 'true'
              steps:
                - template: .pipelines/templates/PackageBuild.yml@self
                  parameters:
                    isCheckBuild: '$(runCheck)'
